name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release